<?xml version="1.0" encoding="utf-8"?>
<!-- $Revision$ -->
<!-- EN-Revision: 322383 Maintainer: yannick Status: ready -->
<!-- Reviewed: no -->

<refentry xml:id="mysqli.connect-error" xmlns="http://docbook.org/ns/docbook">
 <refnamediv>
  <refname>mysqli::$connect_error</refname>
  <refname>mysqli_connect_error</refname>
  <refpurpose>Retourne le message d'erreur de connexion MySQL</refpurpose>
 </refnamediv>

 <refsect1 role="description">
  &reftitle.description;
  <para>&style.oop;</para>
  <fieldsynopsis><type>string</type><varname linkend="mysqli.connect-error">mysqli->connect_error</varname></fieldsynopsis>
  <para>&style.procedural;</para>
  <methodsynopsis>
   <type>string</type><methodname>mysqli_connect_error</methodname>
   <void />
  </methodsynopsis>
  <para>
   Retourne un message d'erreur, lié au dernier appel à
   <function>mysqli_connect</function>.
  </para>
 </refsect1>

 <refsect1 role="returnvalues">
  &reftitle.returnvalues;
  <para>
   Une chaîne qui décrit l'erreur ou &null; si aucune erreur ne survient.
  </para>
 </refsect1>

 <refsect1 role="examples">
  &reftitle.examples;
  <example>
   <title>Exemple avec <varname>$mysqli->connect_error</varname></title>
   <para>&style.oop;</para>
   <programlisting role="php">
<![CDATA[
<?php
$mysqli = @new mysqli('localhost', 'fake_user', 'my_password', 'my_db');

// Fonctionne depuis PHP 5.2.9 et 5.3.0.
if ($mysqli->connect_error) {
    die('Erreur de connexion : ' . $mysqli->connect_error);
}
?>
]]>
   </programlisting>
   <para>&style.procedural;</para>
   <programlisting role="php">
<![CDATA[
<?php
$link = @mysqli_connect('localhost', 'fake_user', 'my_password', 'my_db');

if (!$link) {
    die('Erreur de connexion : ' . mysqli_connect_error());
}
?>
]]>
   </programlisting>
   &examples.outputs;
   <screen>
<![CDATA[
Erreur de connexion : Access denied for user 'fake_user'@'localhost' (using password: YES)
]]>
   </screen>
  </example>
 </refsect1>

 <refsect1 role="notes">
  &reftitle.notes;
  <warning>
   <para>
    La propriété mysqli-&gt;connect_error ne fonctionne correctement que
    depuis PHP versions 5.2.9 et 5.3.0.
    Utilisez la fonction <function>mysqli_connect_error</function>
    pour les versions antérieures.
   </para>
  </warning>
 </refsect1>

 <refsect1 role="seealso">
  &reftitle.seealso;
  <para>
   <simplelist>
    <member><function>mysqli_connect</function></member>
    <member><function>mysqli_connect_errno</function></member>
    <member><function>mysqli_errno</function></member>
    <member><function>mysqli_error</function></member>
    <member><function>mysqli_sqlstate</function></member>
   </simplelist>
  </para>
 </refsect1>

</refentry>

<!-- Keep this comment at the end of the file
Local variables:
mode: sgml
sgml-omittag:t
sgml-shorttag:t
sgml-minimize-attributes:nil
sgml-always-quote-attributes:t
sgml-indent-step:1
sgml-indent-data:t
indent-tabs-mode:nil
sgml-parent-document:nil
sgml-default-dtd-file:"~/.phpdoc/manual.ced"
sgml-exposed-tags:nil
sgml-local-catalogs:nil
sgml-local-ecat-files:nil
End:
vim600: syn=xml fen fdm=syntax fdl=2 si
vim: et tw=78 syn=sgml
vi: ts=1 sw=1
-->
