<?xml version="1.0" encoding="utf-8"?>
<!-- $Revision$ -->
<!-- EN-Revision: 341756 Maintainer: yago Status: ready -->
<!-- Reviewed: no Maintainer: seros -->

<refentry xml:id="exception.getprevious" xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink">
 <refnamediv>
  <refname>Exception::getPrevious</refname>
  <refpurpose>Devuelve la excepción anterior</refpurpose>
 </refnamediv>
 
 <refsect1 role="description">
  &reftitle.description;
  <methodsynopsis>
   <modifier>final</modifier> <modifier>public</modifier> <type>Throwable</type><methodname>Exception::getPrevious</methodname>
   <void />
  </methodsynopsis>
  <para>
   Devuelve la excepción anterior (el tercer parámetro de <methodname>Exception::__construct</methodname>).
  </para>
 </refsect1>
 
 <refsect1 role="parameters">
  &reftitle.parameters;
  &no.function.parameters;
 </refsect1>
 
 <refsect1 role="returnvalues">
  &reftitle.returnvalues;
  <para>
   Devuelve la <classname>Throwable</classname> anterior si está disponible
   o &null; si no.
  </para>
 </refsect1>

 <refsect1 role="changelog">
  &reftitle.changelog;
  <para>
   <informaltable>
    <tgroup cols="2">
     <thead>
      <row>
       <entry>&Version;</entry>
       <entry>&Description;</entry>
      </row>
     </thead>
     <tbody>
      <row>
       <entry>7.0.0</entry>
       <entry>
        La declaración de tipo de retorno cambió a  <classname>Throwable</classname>.
       </entry>
      </row>
     </tbody>
    </tgroup>
   </informaltable>
  </para>
 </refsect1>

 <refsect1 role="examples">
  &reftitle.examples;
  <para>
   <example>
    <title>Ejemplo de <methodname>Exception::getPrevious</methodname></title>
    <para>
     Recorrer, e imprimir la traza de una excepción.
    </para>
    <programlisting role="php">
<![CDATA[
<?php
class MiPropiaExcepción extends Exception {}

function hacerCosas() {
    try {
        throw new InvalidArgumentException("¡Lo está haciendo mal!", 112);
    } catch(Exception $e) {
        throw new MiPropiaExcepción("Ocurrió algo", 911, $e);
    }
}


try {
    hacerCosas();
} catch(Exception $e) {
    do {
        printf("%s:%d %s (%d) [%s]\n", $e->getFile(), $e->getLine(), $e->getMessage(), $e->getCode(), get_class($e));
    } while($e = $e->getPrevious());
}
?>
]]>
    </programlisting>
    &example.outputs.similar;
    <screen>
<![CDATA[
/home/bjori/ex.php:8 Ocurrió algo (911) [MiPropiaExcepción]
/home/bjori/ex.php:6 ¡Lo está haciendo mal! (112) [InvalidArgumentException]
]]>
    </screen>
   </example>
  </para>
 </refsect1>
 
 <refsect1 role="seealso">
  &reftitle.seealso;
   <para>
    <simplelist>
     <member><methodname>Throwable::getPrevious</methodname></member>
    </simplelist>
   </para>
 </refsect1>
</refentry>

<!-- Keep this comment at the end of the file
Local variables:
mode: sgml
sgml-omittag:t
sgml-shorttag:t
sgml-minimize-attributes:nil
sgml-always-quote-attributes:t
sgml-indent-step:1
sgml-indent-data:t
indent-tabs-mode:nil
sgml-parent-document:nil
sgml-default-dtd-file:"~/.phpdoc/manual.ced"
sgml-exposed-tags:nil
sgml-local-catalogs:nil
sgml-local-ecat-files:nil
End:
vim600: syn=xml fen fdm=syntax fdl=2 si
vim: et tw=78 syn=sgml
vi: ts=1 sw=1
-->

